image: "nixos/unstable"
sources:
  - https://github.com/diamondburned/gotktrix
packages:
  - nixos.git
  - nixos.go_1_17
  - nixos.gotools
  - nixos.goimports
artifacts:
  - artifacts/gotktrix-nixos-x86_64
  - artifacts/gotktrix-linux-x86_64
  - artifacts/gotktrix-nixos-aarch64
  - artifacts/gotktrix-linux-aarch64
tasks:
  - prepare: |-
      mkdir artifacts
      touch artifacts/gotktrix-nixos-x86_64
      touch artifacts/gotktrix-linux-x86_64
      touch artifacts/gotktrix-nixos-aarch64
      touch artifacts/gotktrix-linux-aarch64

  - gomod: |-
      cd gotktrix
      go mod tidy

      if [[ $(git status --porcelain) ]]; then
        git diff | cat
        exit 1
      fi

  - format: |-
      cd gotktrix
      deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
      [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

  - release-check: |-
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || complete-build

  # - nix: |-
  #     cd gotktrix
  #     time nix-shell --run 'true'
  #
  # - build: |-
  #     cd gotktrix
  #     nix-shell --run 'time go build -v ./...'
  #
  # - lint: |-
  #     cd gotktrix
  #     nix-shell --run 'time go vet ./...'
  #     nix-shell --run 'time staticcheck -f stylish ./...'

  - artifact: |-
      cd gotktrix
      nix-build -j1 .nix/cross.nix
