image: "nixos/unstable"
sources:
  - https://github.com/diamondburned/gotktrix
packages:
  - nixos.git
  - nixos.go_1_17
  - nixos.gotools
  - nixos.curl
  - nixos.coreutils
  - nixos.jq
secrets:
  - 82568347-1c9e-406e-8de0-525ee7dd21e2
tasks:
  - gomod: |-
      cd gotktrix
      go mod tidy

      if [[ $(git status --porcelain) ]]; then
        git diff | cat
        exit 1
      fi

  - format: |-
      cd gotktrix
      deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
      [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

  - test-build: |-
      [[ $GITHUB_REF && $GITHUB_REF != *"/release" ]] && exit
      nix-build -j1 .nix/package-impure.nix

  - tagged-build: |-
      [[ $GITHUB_REF != *"/tags/"* ]] && exit
      out="$(cd gotktrix && nix-build -j1 .nix/cross.nix)"

      mkdir artifacts
      cp $out/* ./artifacts/

      bash ./gotktrix/.github/upload-artifacts.sh

