image: "nixos/unstable"
sources:
  - https://github.com/diamondburned/gotktrix
packages:
  - nixos.git
  - nixos.go_1_17
  - nixos.gotools
  - nixos.goimports
artifacts:
  - gotktrix/gotktrix-nixos
  - gotktrix/gotktrix
tasks:
  - format: |-
      cd gotktrix
      deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
      [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

  - gomod: |-
      cd gotktrix
      go mod tidy

      if [[ $(git status --porcelain) ]]; then
        git diff | cat
        exit 1
      fi

  - nix-init: |-
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || exit

      cd gotktrix
      time nix-shell --run 'true'

  - build: |-
      # Everything in lint will require building the binary first, so we might
      # as well do it here.
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || exit

      cd gotktrix
      nix-shell --run 'time go build -v ./...'

  - lint: |-
      # Skip lint here because both vet and staticcheck require building all
      # dependencies.
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || exit

      cd gotktrix
      nix-shell --run 'time go vet ./...'
      nix-shell --run 'time staticcheck -f stylish ./...'

  - artifact: |-
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || exit

      cd gotktrix
      nix-shell --command '
        go build -o gotktrix-nixos

        go build -o gotktrix
        patchelf-x86_64 gotktrix
      '
