image: "nixos/unstable"
sources:
  - https://github.com/diamondburned/gotktrix
packages:
  - nixos.git
  - nixos.go_1_17
  - nixos.gotools
  - nixos.goimports
artifacts:
  - artifacts/gotktrix
  - artifacts/gotktrix-nixos
tasks:
  - prepare: |-
      mkdir artifacts
      touch artifacts/gotktrix
      touch artifacts/gotktrix-nixos

  - gomod: |-
      cd gotktrix
      go mod tidy

      if [[ $(git status --porcelain) ]]; then
        git diff | cat
        exit 1
      fi

  - format: |-
      cd gotktrix
      deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
      [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

  - release-check: |-
      [[ ! $GITHUB_REF || $GITHUB_REF == *"/release" ]] || complete-build

  - nix: |-
      cd gotktrix
      time nix-shell --run 'true'

  - build: |-
      cd gotktrix
      nix-shell --run 'time go build -v ./...'

  - lint: |-
      cd gotktrix
      nix-shell --run 'time go vet ./...'
      nix-shell --run 'time staticcheck -f stylish ./...'

  - artifact: |-
      cd gotktrix
      nix-shell --command '
        go build -o ../artifacts/gotktrix-nixos

        go build -o ../artifacts/gotktrix
        patchelf-x86_64 ../artifacts/gotktrix
      '
